spring.application.name=room-booking

spring.datasource.url=jdbc:postgresql://localhost:5432/room_booking
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true